import { LightningElement, api, track } from 'lwc';
import { FlowAttributeChangeEvent } from 'lightning/flowSupport';

export default class PolymorphicLookupFlowWrapper extends LightningElement {
    // Flow Inputs
    @api label;
    @api objectApiNames; 
    @api iconNames;      
    @api subtitleFields; 
    @api required = false;
    
    // NEW: JSON String input for filters. Example: '{"Account": "BillingCity = \'NY\'"}'
    @api filterJson; 

    // Flow Outputs
    @api selectedRecordId;
    @api selectedObjectType;

    @track computedObjectOptions = [];
    @track computedFilterConfig = {}; // Stores the parsed object

    // STATE VARIABLES
    internalErrorToRender = null; // Error generated by JS logic
    externalErrorToRender = null; // Error generated by Flow Builder

    connectedCallback() {
        this.generateObjectOptions();
        this.parseFilterJson();
    }

    generateObjectOptions() {
        if (!this.objectApiNames) {
            this.computedObjectOptions = [];
            return;
        }

        const names = this.objectApiNames.split(',').map(item => item.trim());
        const icons = this.iconNames ? this.iconNames.split(',').map(item => item.trim()) : [];
        const subtitles = this.subtitleFields ? this.subtitleFields.split(',').map(item => item.trim()) : [];

        this.computedObjectOptions = names.map((apiName, index) => {
            return {
                label: apiName, 
                plural: apiName + 's', 
                value: apiName,
                iconName: icons[index] || 'standard:default', 
                subtitleField: subtitles[index] || 'CreatedDate' 
            };
        });
    }

    parseFilterJson() {
        if (this.filterJson) {
            try {
                // Ensure we handle basic Flow text template issues like smart quotes if necessary, 
                // but usually standard JSON.parse is enough if the admin is careful.
                this.computedFilterConfig = JSON.parse(this.filterJson);
            } catch (error) {
                console.error('PolymorphicLookupFlowWrapper: Invalid JSON in filterJson', error);
                this.computedFilterConfig = {};
            }
        } else {
            this.computedFilterConfig = {};
        }
    }

    handleLookupSelection(event) {
        const { recordId, objectType } = event.detail;
        
        this.selectedRecordId = recordId;
        this.selectedObjectType = objectType;
        //
        // Reset errors on user interaction
        this.internalErrorToRender = null;
        this.externalErrorToRender = null;

        // Optional: Validate immediately on selection/removal
        // this.validate();

        this.dispatchEvent(new FlowAttributeChangeEvent('selectedRecordId', recordId));
        this.dispatchEvent(new FlowAttributeChangeEvent('selectedObjectType', objectType));
    }
    
    // Helper to consolidate logic
    getInternalErrorMessage() {
        if (this.required && !this.selectedRecordId) {
            return 'Please select a record.';
        }
        return null;
    }

    @api
    validate() {
        // 1. Calculate the error
        const internalError = this.getInternalErrorMessage();

        // 2. IMPORTANT: Update the UI variable immediately
        this.internalErrorToRender = internalError;

        // 3. Return the status to the Flow Engine
        if (internalError) {
            return { 
                isValid: false, 
                errorMessage: internalError 
            };
        }

        return { isValid: true };
    }

    @api
    setCustomValidity(externalErrorMessage) {
        // This is called by Flow when a Flow-level validation rule fails.
        // It is ALSO called with empty string to clear errors before validation.
        this.externalErrorToRender = externalErrorMessage;
    }

    @api reportValidity() {
        // This is called to force the component to show its current error state
        if(!this.externalErrorToRender) {
             this.internalErrorToRender = this.getInternalErrorMessage();
        }
    }
    
    // Getter to decide which error to show (External usually takes precedence)
    get errorToRender() {
        return this.externalErrorToRender || this.internalErrorToRender;
    }
}